// eslint-disable-next-line import/prefer-default-export
export const SET_TRANSACTIONS = "SET_TRANSACTIONS";
export const ADD_TRANSACTION = "ADD_TRANSACTION";
export const DELETE_TRANSACTION = "DELETE_TRANSACTION";
export const CREATE_OR_UPDATE_TRANSACTION = "CREATE_OR_UPDATE_TRANSACTION";
export const ALL_MONTHS_PENDING = "ALL_MONTHS_PENDING";
export const ALL_MONTHS_SET = "ALL_MONTHS_SET";
export const ALL_MONTHS_ADD = "ALL_MONTHS_ADD";
export const MONTH_STATS_PENDING = "MONTH_STATS_PENDING";
export const MONTH_STATS_SET = "MONTH_STATS_SET";
export const MONTH_TRANSACTIONS_PENDING = "MONTH_TRANSACTIONS_PENDING";
export const MONTH_TRANSACTIONS_SET = "MONTH_TRANSACTIONS_SET";
